### ISSUE TITLE
Build on OSX not implemented

### ISSUE THREAD

**Issue by rcedgar** [rcedgar/usearch12#1]
If you're interested in implementing this, please reply below (to avoid duplicate assignment of the task).

**Comment by TongZhou2017** [comment]
get an error while using @igortru [osx binary file](https://github.com/rcedgar/usearch12/releases/download/v12.0-beta1/usearch12_osx12.0-beta) in M2:
`zsh: illegal hardware instruction`

**Comment by jianshu93** [comment]
Hello all, I build it successfully on M series chip via GCC. A universal binary is attached. I will also add usearch to homebrew soon. 

Jianshu


Universal binary:

[usearch_Darwin_universal.zip](https://github.com/user-attachments/files/15848473/usearch_Darwin_universal.zip)

**Comment by rcedgar** [comment]
Release 12.0-beta has been updated with binaries for Linux x86 & aarch64 and also OSX with M & x66:

[https://github.com/rcedgar/usearch12/releases](https://github.com/rcedgar/usearch12/releases)

Actions have been implemented to generate binaries for five platforms (Windows, 2xLinux and 2xOSX) with thanks to @igortru !

**Comment by rcedgar** [comment]
Closing as completed by the Actions.
