### ISSUE TITLE
naive bayesian classifier also not in open source v12

### ISSUE THREAD

**Issue by jianshu93** [rcedgar/usearch12#11]
Hello @rcedgar,

I noticed that the NBC algorithm is also not there in v12, which is widely used for amplicon/marker gene classification. Again I understand that we can rely on the binary for v11.0.667 but cannot make it built in in other pipelines or softwares. Sintax ia available though an alternative to NBC.

Just to ask and I will close this issue soon. 

Jianshu

**Comment by rcedgar** [comment]
As noted in the README

<pre>
Compared to earlier versions, functionality which is sufficiently covered by
other open-source projects has been removed...The goal here is to simplify
the package as much as reasonably possible 
</pre>

The NBC algorithm is here:

https://github.com/rdpstaff/classifier

It's also implemented in DADA2. SINTAX is faster and uses less memory.
