### ISSUE TITLE
add usearch12 to bioconda

### ISSUE THREAD

**Issue by jianshu93** [rcedgar/usearch12#14]
Hi @rcedgar,

Just wonder whether it is possible to also add the open source version 12 to bioconda, so that users can easily installed it without compiling from source. The bioconda formula is a little bit weird but should be easy to just follow other examples (e.g. other C/C++ formula packages).

Thanks,
Jianshu

**Comment by rcedgar** [comment]
No idea, would be great if someone would contribute this work!

**Comment by jianshu93** [comment]
I would be happy to do it and keep you updated！

Jianshu

**Comment by cjfields** [comment]
@jianshu93 see https://github.com/bioconda/bioconda-recipes/pull/48562
