### ISSUE TITLE
Request to reintegrate the `calc_distmx` command

### ISSUE THREAD

**Issue by vmikk** [rcedgar/usearch12#6]
Hello Robert,

First and foremost, I would like to extend my deepest gratitude for your decision to open-source USEARCH. This move is greatly appreciated by the bioinformatics community and will undoubtedly foster an environment of increased collaboration.

I am writing to inquire about the possibility of reintegrating the `calc_distmx` command into the open-source version of USEARCH. While I understand and support the rationale behind simplifying the project, I believe that the `calc_distmx` command is quite unique and is not covered by other projects. It has been particularly useful for many users, including our team.

Thank you for considering this request.
With kind regards,
Vladimir

**Comment by rcedgar** [comment]
Could you use the binary for a previous version?
 [https://github.com/rcedgar/usearch_old_binaries/](https://github.com/rcedgar/usearch_old_binaries/)

**Comment by vmikk** [comment]
Thank you for sharing the binaries. I appreciate your efforts in making this available!
