### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by KasperSkytte** [rcedgar/usearch12#7]
In the [installation instructions](https://rcedgar.github.io/usearch12_documentation/install.html) there's a dead link here

![image](https://github.com/rcedgar/usearch12/assets/23030537/9764fedf-6490-4dcc-aa01-25d03ffffcfd)

The path https://rcedgar.github.io/usearch12_documentation/vcomp100.html gives 404.

**Comment by rcedgar** [comment]
Thanks for the heads up. This issue belongs in the documentation repo [https://github.com/rcedgar/usearch12_documentation/](https://github.com/rcedgar/usearch12_documentation/).

**Comment by rcedgar** [comment]
Fixed.
