### ISSUE TITLE
-fastq_mergepairs not accepting wildcards?

### ISSUE THREAD

**Issue by telatin** [rcedgar/usearch12#9]
Hi @rcedgar,
I'm testing the new version to draft a q2 wrapper.

With USEARCH 11 the following command works:

```
usearch  -fastq_mergepairs *R1*fastq -relabel @ -fastqout ../usearch/merge.fq
```

with usearch12 the wildcard expansion is not accepted:
```
Command line error, unexpected 'sample4_S0_L000_R1_001.fastq'
```

but wildcard seems supported according [to the docs](https://rcedgar.github.io/usearch12_documentation/cmd_fastq_mergepairs.html).

**Comment by rcedgar** [comment]
This is a documentation error, wildcards are not supported in v12.
